site_name: AppBox Docs
site_description: AppBox Documentation
site_url: https://docs.getappbox.com
copyright: Copyright © AppBox
repo_url: https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation
repo_name: AppBox
remote_branch: master
dev_addr: 127.0.0.1:2000 

# Google Analytics
google_analytics:
  - 'UA-85215717-4'
  - 'auto'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation'
    - type: 'twitter'
      link: 'https://twitter.com/tryappbox'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
pages:
- Home: index.md
- Getting Started: 
  - How to use AppBox?: GettingStarted/useappbox.md
- Continuous Integration:
  - How to use AppBox with Jenkins and GitLab for CI and CD?: ContinuousIntegration/usewithjenkinsandgitlab.md
- Features: 
  - Keep Same Link: Features/keepsamelink.md
  - Upload Chunk Size: Features/uploadchunksize.md
  - Download IPA file from AppBox Installation Webpage: Features/downloadipa.md
  - Get Application Details on AppBox Installation Web Page: Features/moredetails.md
- FAQs:
  - How to delete an uploaded app or disable a link on AppBox?: FAQs/deleteapplication.md
  - Is there any installation limit per app on AppBox?: FAQs/installationlimit.md
  - How long will Application Installation links be available on AppBox?: FAQs/installationlinkexpire.md
  - What is the Maximum Upload Application Size?: FAQs/maximumuploadsize.md
  - How to share Xcode Project Schemes?: FAQs/sharexcodeprojectschemes.md