name: Issue Activity

on:
  issues:
    types: [opened, edited, reopened, closed]
    
jobs:
  slack_notification:
    runs-on: ubuntu-latest
    env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: 'AppBox Github Bot'
        SLACK_OVERRIDE_MESSAGE: ''
    steps:
      - uses: Ilshidur/action-slack@c56582d
        with:
          args: '\n\nTitle - {{ EVENT_PAYLOAD.issue.title }} \n\nIssue Activity - {{ EVENT_PAYLOAD.action }}.  \n\nURL - {{ EVENT_PAYLOAD.issue.html_url }} \n\nBody - {{ EVENT_PAYLOAD.issue.body }}'
          
