name: Issue Comment Activity

on:
  issue_comment:
    types: [created, edited, deleted]
    
jobs:
  slack_notification:
    runs-on: ubuntu-latest
    env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: 'AppBox Github Bot'
    steps:
      - uses: Ilshidur/action-slack@c56582d
        with:
          args: '\n\nBody - {{ EVENT_PAYLOAD.comment.body }} \n\nIssue Activity - {{ EVENT_PAYLOAD.action }}.  \n\nURL - {{ EVENT_PAYLOAD.comment.html_url }} \n\nBy - {{ EVENT_PAYLOAD.comment.user.login }}'
